import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "w-screen h-full bg-gradient-to-b from-blue-50 to-red-100"
        )}
      >
        <main className="h-full">
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-full pt-10">{children}</div>
        </main>
      </body>
    </html>
  );
}
