import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TransitionProvider from "@/components/transitionProvider";
import Navbar from "../components/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Georgee Flash Portfolio",
  description: "My creative animated portfolio generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //bg-gradient-to-b from-blue-50 to-red-100
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          `${poppins.className} antialiased flex flex-col`,
          "h-full bg-blue-50",
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        <TransitionProvider>
          <nav className="h-[5rem] md:h-24 z-50 bg-green-100 top-0">
            <Navbar />
          </nav>
          <main className="pt-4 h-ful">{children}</main>
        </TransitionProvider>
      </body>
    </html>
  );
}

/* 
<div class="relative h-full w-full bg-black"><div class="absolute bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div><div class="absolute left-0 right-0 top-[-10%] h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_400px_at_50%_300px,#fbfbfb36,#000)]"></div></div>
*/
